service: sms-gateway

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1
  environment: ${file(secrets.yml):${self:custom.stage}}
  timeout: 99
  versionFunctions: false

package:
  exclude:
    - secrets.yml
    - README.md

functions:
  sms:
    handler: handler.sms_handler
    events:
        - http:
            method: post
            path: sms
  birthday:
    handler: handler.birthday_handler
    events:
      - schedule: cron(0 7 * * ? *)

plugins:
  - serverless-python-requirements

custom:
  stage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    dockerizePip: true # for serverless-python-requirements
